#!/bin/bash
find . -type f \( -name "*.gif" \) | while read file; do filename=$(echo "$file" | sed 's/\(.*\)\.gif/\1/') size=$(stat --printf="%s" "$file") echo "$size $filename" done | sort -n | awk '{print $2}'
